#!/bin/bash

File=( 
inputNt8_Ns32_Beta5.7000.txt
inputNt8_Ns32_Beta5.9500.txt
inputNt8_Ns32_Beta6.0000.txt
inputNt8_Ns32_Beta6.1000.txt
inputNt8_Ns32_Beta6.2000.txt
inputNt8_Ns32_Beta6.3500.txt
inputNt8_Ns32_Beta6.5500.txt
inputNt8_Ns32_Beta6.7000.txt
inputNt8_Ns32_Beta6.8500.txt
inputNt8_Ns32_Beta6.9500.txt
 )
#File=()

MyDIR=/wsu/home/fy/fy41/fy4125/Measurement/FullQCDCloverTraceless/AmitPureGauge
a=$1

echo "This is Beta = ("  ${File[$a]} 

INPUT=${MyDIR}/${File[$a]}
echo "Input file used is at "  ${INPUT}
TimeOutput=${MyDIR}/Output/TimeFor${File[$a]}
cd ${MyDIR}

echo "${INPUT}" >> ${TimeOutput}
echo "JOB INFO: Queue=" $PBS_O_QUEUE ",  NodeName="$HOSTNAME   ",  JobName="$PBS_JOBNAME  ",  JobID="$PBS_JOBID >> ${TimeOutput}
echo "mpirun -np 8 ./su3_ora  ${INPUT}" >> ${TimeOutput}
echo $(date) >> ${TimeOutput}

mpirun -np 8 ./su3_ora  ${File[$a]}  

echo $(date) >>  ${TimeOutput}
