#!/bin/bash
Nt=$1
Ns=$2
BetaIndex=$3
ncpus=$4
MyDIR=/wsu/home/fy/fy41/fy4125//AmitPureGauge
cd ${MyDIR}

BetaNameNs16=(
Beta5.3500
Beta5.6000
Beta5.7000
Beta5.8000
Beta5.9000
Beta6.0000
Beta6.2000
Beta6.3500
Beta6.5000
Beta6.6000
)

BetaNameNs24=(
Beta5.6000
Beta5.8500
Beta5.9000
Beta6.0000
Beta6.1000
Beta6.2500
Beta6.4500
Beta6.6000
Beta6.7500
Beta6.8500
)

BetaNameNs32=(
Beta5.7000
Beta5.9500
Beta6.0000
Beta6.1000
Beta6.2000
Beta6.3500
Beta6.5500
Beta6.7000
Beta6.8500
Beta6.9500
 )

read -a BETAInputFile <<< $(eval echo \${BetaNameNs${Ns}[${BetaIndex}]})


File=inputNt${Nt}_Ns${Ns}_${BETAInputFile}.txt

INPUT=${MyDIR}/Nt${Nt}Input/${File}
TimeOutput=${MyDIR}/OutputNt${Nt}/TimeFor${File}

echo "${INPUT}" >> ${TimeOutput}
echo "JOB INFO: Queue=" $PBS_O_QUEUE ",  NodeName="$HOSTNAME   ",  JobName="$PBS_JOBNAME  ",  JobID="$PBS_JOBID >> ${TimeOutput}
echo "mpirun -np ${ncpus} ./su3_ora  ${INPUT} /dev/null /dev/null  /wsu/tmp/AmitConfiguration  OutputNt${Nt}" >> ${TimeOutput}
echo $(date) >> ${TimeOutput}

mpirun -np ${ncpus} ./su3_ora ${INPUT} /dev/null /dev/null  /wsu/tmp/AmitPureGauge   OutputNt${Nt}  > /dev/null

echo $(date) >>  ${TimeOutput}
