#!/bin/bash

#File=(inputNt4_beta6p0.txt inputNt4_beta6p8.txt  inputNt4_beta8p0.txt)
File=(inputNt6_beta6p0.txt inputNt4_beta6p8.txt  inputNt4_beta8p0.txt)
MyDIR=/wsu/home/fy/fy41/fy4125/Lattice/milc/MyFFApp
a=$1

echo "This is Beta = ("  ${File[$a]} 

INPUT=${MyDIR}/Run1Input/${File[$a]}
#SCREENOUTPUT=/wsu/home/fy/fy41/fy4125/Log/ScreenOutput${Beta[$a]}.out
echo "Input file used is at "  ${INPUT}
#echo "Screenoutput is at " ${SCREENOUTPUT}
TimeOutput=${MyDIR}/OutPut/TimeFor${File[$a]}
# . /wsu/home/fy/fy41/fy4125/.bashrc
cd ${MyDIR}

echo "${INPUT}" >> ${TimeOutput}
echo "mpirun -np 64 ./su3_rhmc_hisq  ${INPUT}" >> ${TimeOutput}
echo $(date) >> ${TimeOutput}

mpirun -np 64 ./su3_rhmc_hisq  ${INPUT} 

echo $(date) >>  ${TimeOutput}
